spring.application.name=resume-ai-saas

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Google GenAI Configuration
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash